Date: Thu, 20 Nov 1997 15:44:35 GMT
Server: Apache/1.2.1 Ben-SSL/1.8
Last-Modified: Tue, 04 Nov 1997 20:57:46 GMT
ETag: "2d986-9b1-345f8c4a"
Content-Length: 2481
Accept-Ranges: bytes
Connection: close
Content-Type: text/html

<HTML><HEAD><TITLE>Mesa Air Group - Welcome Aboard!</TITLE><META  name="description" content="Welcome to Mesa Air Group's Web site!  Here you will find links to our airlines, financial reports, Mesa Air Group's history, and more.  Again, thank you for visiting and welcome!"><META name="keywords" content="mesa airlines,mesa air group,mesa air,america west air,florida west,airlines,aircraft,new mexico,colorado,usaair airlines,reserver tickets,airline tickets,ticket information,flight schedule,airline schedule,united express airlines,mesa air,prop planes,fokker jet,mesa pilot development,flight school,pilot school,san juan college flight school,become a pilot,pilot training,training,pilot,flight training"> </HEAD><FRAMESET COLS="18%,82%" FRAMEBORDER="NO"  BORDER="0" FRAMESPACING="0">              <FRAME Src="navigation.htm" NAME="secondary" SCROLLING="No">         <FRAME Src="home.htm"  NAME="primary"></FRAMESET><!--No Frames! --><NOFRAMES>	<BODY><H1>This page looks best with frames!</H1><BODY BGCOLOR="#FFFFFF"><CENTER>This page looks better in a browser that can display frames.Go <A HREF="www.netscape.com">HERE</A> or <A HREF="www.microsoft.com">HERE</A> to get one!</CENTER><FONT COLOR="FFFFFF">mesa airlines,mesa air group,mesa air,america west air,florida west,airlines,aircraft,new mexico,colorado,usaair airlines,reserver tickets,airline tickets,ticket information,flight schedule,airline schedule,united express airlines,mesa air,prop planes,fokker jet,mesa pilot development,flight school,pilot school,san juan college flight school,become a pilot,pilot training,training,pilot,flight training,mesa airlines,mesa air group,mesa air,america west air,florida west,airlines,aircraft,new mexico,colorado,usaair airlines,reserver tickets,airline tickets,ticket information,flight schedule,airline schedule,united express airlines,mesa air,prop planes,fokker jet,mesa pilot development,flight school,pilot school,san juan college flight school,become a pilot,pilot training,training,pilot,flight training,mesa airlines,mesa air group,mesa air,america west air,florida west,airlines,aircraft,new mexico,colorado,usaair airlines,reserver tickets,airline tickets,ticket information,flight schedule,airline schedule,united express airlines,mesa air,prop planes,fokker jet,mesa pilot development,flight school,pilot school,san juan college flight school,become a pilot,pilot training,training,pilot,flight training</FONT></BODY></NOFRAMES></HTML>